---
# tasks file for swarm-join
- name: Add nodes
  community.docker.docker_swarm:
    state: join
    advertise_addr: swarmworker
    join_token: "{{ hostvars['swarmmanager']['result']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarmmanager' ]

